var isMale = true;
var isFemale = false;
var age = 35;
var weight = 83;
var imaginarySalary = 123447865;
var firstName = "Nazar";
var lastName = 'Volkov';
var someText = "This my name: " + firstName + ", and lastname " + lastName;
console.log(someText);
var arr = [];
arr.push(34);
